"use client";

import { FormEvent, type ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { KeyRound, Plus, RefreshCw, Save, ShieldCheck, UserCheck, UserX } from "lucide-react";
import { adminRequest } from "@/lib/admin-client";
import type { RoleAdministration, RoleItem, UserItem } from "@/lib/admin-types";
import { EmptyState, ErrorPanel, fieldClass, LoadingPanel, primaryButton, secondaryButton, StatusBadge, useToast } from "./admin-ui";

export function UsersSection() {
  const { notify } = useToast(); const [users, setUsers] = useState<UserItem[]>([]); const [roles, setRoles] = useState<RoleItem[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState("");
  const [creating, setCreating] = useState(false); const [selected, setSelected] = useState<UserItem | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [accounts, administration] = await Promise.all([adminRequest<UserItem[]>(`/admin/manage/transport/users${search ? `?q=${encodeURIComponent(search)}` : ""}`), adminRequest<RoleAdministration>("/admin/manage/transport/roles")]); setUsers(accounts); setRoles(administration.roles); } catch (reason) { setError(reason instanceof Error ? reason.message : "Users could not be loaded."); } finally { setLoading(false); } }, [search]);
  useEffect(() => { void load(); }, [load]);
  async function action(input: Record<string, unknown>, message: string) { setBusy(true); try { await adminRequest("/admin/manage/transport/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); notify(message); setSelected(null); setCreating(false); await load(); } catch (reason) { notify(reason instanceof Error ? reason.message : "User operation failed.", "error"); } finally { setBusy(false); } }
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 border-y border-slate-200 bg-white p-4 sm:flex-row sm:items-center"><label className="flex-1 text-sm font-medium">Search users<input className={`${fieldClass} mt-1`} value={search} onChange={event => setSearch(event.target.value)} placeholder="Email or display name" /></label><div className="flex gap-2 sm:pt-6"><button className={secondaryButton} onClick={() => void load()}><RefreshCw className="size-4" />Refresh</button><button className={primaryButton} onClick={() => setCreating(true)}><Plus className="size-4" />Add user</button></div></div>
    {loading && users.length === 0 ? <LoadingPanel label="Loading users" /> : error ? <ErrorPanel message={error} onRetry={() => void load()} /> : users.length === 0 ? <EmptyState title="No users found" detail="Create an explicitly authorized account or change the search." /> : <div className="overflow-x-auto border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">User</th><th className="p-3">Status</th><th className="p-3">Roles</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{users.map(user => <tr key={user.id} className="border-t border-slate-200"><td className="p-3"><strong className="block">{user.display_name}</strong><span className="text-slate-500">{user.email}</span></td><td className="p-3"><StatusBadge value={user.state} /></td><td className="p-3"><div className="flex flex-wrap gap-1">{user.roles.map(role => <code key={role} className="rounded bg-slate-100 px-2 py-1 text-xs">{role}</code>)}</div></td><td className="p-3"><div className="flex justify-end gap-2"><button className={secondaryButton} onClick={() => setSelected(user)}>Manage</button><button className={secondaryButton} onClick={() => void action({ action: user.state === "active" ? "disable" : "enable", id: user.id }, user.state === "active" ? "User disabled." : "User enabled.")}>{user.state === "active" ? <UserX className="size-4" /> : <UserCheck className="size-4" />}{user.state === "active" ? "Disable" : "Enable"}</button></div></td></tr>)}</tbody></table></div>}
    {creating && <CreateUserDialog roles={roles} busy={busy} onCancel={() => setCreating(false)} onSubmit={values => void action(values, "User created.")} />}
    {selected && <ManageUserDialog user={selected} roles={roles} busy={busy} onCancel={() => setSelected(null)} onSubmit={(values, message) => void action(values, message)} />}
  </div>;
}

function CreateUserDialog({ roles, busy, onCancel, onSubmit }: { roles: RoleItem[]; busy: boolean; onCancel: () => void; onSubmit: (value: Record<string, unknown>) => void }) {
  const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState(roles[0]?.id ?? "");
  function submit(event: FormEvent) { event.preventDefault(); onSubmit({ action: "create", email, display_name: name, password, roles: [role] }); }
  return <Dialog title="Add user" onCancel={onCancel}><form onSubmit={submit} className="space-y-4"><Field label="Email" type="email" value={email} onChange={setEmail} /><Field label="Display name" value={name} onChange={setName} /><Field label="Temporary password (12+ characters)" type="password" value={password} onChange={setPassword} minLength={12} /><label className="block text-sm font-medium">Initial role<select className={`${fieldClass} mt-1`} value={role} onChange={event => setRole(event.target.value)}>{roles.map(item => <option key={item.id} value={item.id}>{item.name} ({item.id})</option>)}</select></label><Actions busy={busy} onCancel={onCancel} label="Create user" /></form></Dialog>;
}

function ManageUserDialog({ user, roles, busy, onCancel, onSubmit }: { user: UserItem; roles: RoleItem[]; busy: boolean; onCancel: () => void; onSubmit: (value: Record<string, unknown>, message: string) => void }) {
  const [assigned, setAssigned] = useState(new Set(user.roles)); const [password, setPassword] = useState("");
  return <Dialog title={`Manage ${user.display_name}`} onCancel={onCancel}><fieldset><legend className="text-sm font-semibold">Explicit roles</legend><div className="mt-2 grid gap-2">{roles.map(role => <label key={role.id} className="flex items-center gap-3 rounded border border-slate-200 p-3 text-sm"><input type="checkbox" checked={assigned.has(role.id)} onChange={() => setAssigned(current => toggleSet(current, role.id))} />{role.name}<code className="ml-auto text-xs text-slate-500">{role.id}</code></label>)}</div><button className={`${primaryButton} mt-3`} disabled={busy || assigned.size === 0} onClick={() => onSubmit({ action: "assign_roles", id: user.id, roles: [...assigned] }, "User roles updated.")}><Save className="size-4" />Save roles</button></fieldset><div className="mt-6 border-t border-slate-200 pt-4"><Field label="New password (12+ characters)" type="password" value={password} onChange={setPassword} minLength={12} /><button className={`${secondaryButton} mt-3`} disabled={busy || password.length < 12} onClick={() => onSubmit({ action: "reset_password", id: user.id, password }, "Password reset; existing sessions were invalidated.")}><KeyRound className="size-4" />Reset password</button></div></Dialog>;
}

export function RolesSection() {
  const { notify } = useToast(); const [data, setData] = useState<RoleAdministration>({ roles: [], permissions: [] }); const [selected, setSelected] = useState<string>(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const value = await adminRequest<RoleAdministration>("/admin/manage/transport/roles"); setData(value); setSelected(current => current || value.roles[0]?.id || ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Roles could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]); const role = data.roles.find(item => item.id === selected); const [creating, setCreating] = useState(false);
  async function mutate(input: Record<string, unknown>, method: "POST" | "DELETE" = "POST") { setBusy(true); try { await adminRequest("/admin/manage/transport/roles", { method, headers: { "content-type": "application/json" }, body: JSON.stringify(input) }); notify("Role permissions updated."); await load(); } catch (reason) { notify(reason instanceof Error ? reason.message : "Role operation failed.", "error"); } finally { setBusy(false); } }
  if (loading && data.roles.length === 0) return <LoadingPanel label="Loading roles and permissions" />; if (error) return <ErrorPanel message={error} onRetry={() => void load()} />;
  return <div className="grid gap-5 lg:grid-cols-[18rem_1fr]"><aside className="border border-slate-200 bg-white p-3"><div className="flex items-center justify-between p-2"><h2 className="font-semibold">Roles</h2><button className={secondaryButton} onClick={() => setCreating(true)}><Plus className="size-4" />Add</button></div>{data.roles.map(item => <button key={item.id} onClick={() => setSelected(item.id)} className={`mt-1 w-full rounded p-3 text-left text-sm ${selected === item.id ? "bg-sky-50 text-sky-900" : "hover:bg-slate-50"}`}><strong className="block">{item.name}</strong><span className="text-xs text-slate-500">{item.id} · {item.users} users{item.built_in ? " · built-in" : ""}</span></button>)}</aside>{role && <PermissionMatrix role={role} permissions={data.permissions} busy={busy} onSave={values => void mutate({ action: "permissions", id: role.id, permissions: values })} onDelete={() => void mutate({ id: role.id }, "DELETE")} />}{creating && <CreateRoleDialog busy={busy} onCancel={() => setCreating(false)} onSubmit={value => { setCreating(false); void mutate(value); }} />}</div>;
}
function PermissionMatrix({ role, permissions, busy, onSave, onDelete }: { role: RoleItem; permissions: RoleAdministration["permissions"]; busy: boolean; onSave: (values: string[]) => void; onDelete: () => void }) {
  const [grants, setGrants] = useState(new Set(role.permissions)); useEffect(() => setGrants(new Set(role.permissions)), [role]); const groups = useMemo(() => { const value = new Map<string, typeof permissions>(); for (const item of permissions) value.set(item.group, [...(value.get(item.group) ?? []), item]); return value; }, [permissions]);
  return <section className="border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-sky-700">Explicit PermissionEngine grants</p><h2 className="mt-1 text-lg font-semibold">{role.name}</h2><p className="text-sm text-slate-500">{role.id}{role.built_in ? " · protected, release-managed built-in role" : ""}</p></div>{!role.built_in && <button className={primaryButton} disabled={busy} onClick={() => onSave([...grants])}><Save className="size-4" />Save permissions</button>}</div><div className="mt-5 space-y-5">{[...groups].map(([group, items]) => <fieldset key={group} disabled={role.built_in}><legend className="flex items-center gap-2 font-semibold"><ShieldCheck className="size-4 text-sky-700" />{group}</legend><div className="mt-2 grid gap-2 md:grid-cols-2">{items.map(item => <label key={item.id} className="flex items-start gap-3 rounded border border-slate-200 p-3 text-sm"><input type="checkbox" className="mt-1" checked={grants.has(item.id)} onChange={() => setGrants(current => toggleSet(current, item.id))} /><span><strong className="block font-medium">{item.action.replaceAll("_", " ")} {item.resource_type.replaceAll("_", " ")}</strong><code className="text-xs text-slate-500">{item.id}</code></span></label>)}</div></fieldset>)}</div>{!role.built_in && <div className="mt-6 border-t border-red-100 pt-4"><button className={secondaryButton} disabled={busy || role.users > 0} onClick={onDelete}>Delete unused role</button>{role.users > 0 && <p className="mt-2 text-xs text-slate-500">Remove this role from all users before deleting it.</p>}</div>}</section>;
}

function CreateRoleDialog({ busy, onCancel, onSubmit }: { busy: boolean; onCancel: () => void; onSubmit: (value: Record<string, unknown>) => void }) { const [id, setId] = useState(""); const [name, setName] = useState(""); return <Dialog title="Add custom role" onCancel={onCancel}><form onSubmit={event => { event.preventDefault(); onSubmit({ action: "create", id, name }); }} className="space-y-4"><Field label="Role ID (lowercase and hyphens)" value={id} onChange={setId} /><Field label="Readable name" value={name} onChange={setName} /><Actions busy={busy} onCancel={onCancel} label="Create role" /></form></Dialog>; }
function Dialog({ title, onCancel, children }: { title: string; onCancel: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/45 p-4"><section role="dialog" aria-modal="true" aria-labelledby="admin-dialog-title" className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-md bg-white p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 id="admin-dialog-title" className="text-lg font-semibold">{title}</h2><button className={secondaryButton} onClick={onCancel}>Close</button></div>{children}</section></div>; }
function Field({ label, value, onChange, type = "text", minLength }: { label: string; value: string; onChange: (value: string) => void; type?: string; minLength?: number }) { return <label className="block text-sm font-medium">{label}<input required type={type} minLength={minLength} className={`${fieldClass} mt-1`} value={value} onChange={event => onChange(event.target.value)} /></label>; }
function Actions({ busy, onCancel, label }: { busy: boolean; onCancel: () => void; label: string }) { return <div className="flex justify-end gap-2 border-t border-slate-200 pt-4"><button type="button" className={secondaryButton} onClick={onCancel}>Cancel</button><button className={primaryButton} disabled={busy}>{label}</button></div>; }
function toggleSet(current: Set<string>, value: string) { const next = new Set(current); if (next.has(value)) next.delete(value); else next.add(value); return next; }
